# Generated by Django 4.2 on 2024-12-29 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='image brand'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='group title')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='group photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description group')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is_active')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productgroup', verbose_name='parent group')),
            ],
            options={
                'verbose_name': 'product group',
                'verbose_name_plural': 'product groups',
            },
        ),
    ]
