# Generated by Django 4.2 on 2024-12-29 19:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_image_name_alter_productgroup_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=100, verbose_name='value title')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='products.feature', verbose_name='feature')),
            ],
            options={
                'verbose_name': 'feature value',
                'verbose_name_plural': 'feature values',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='product name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('summary_description', models.TextField(blank=True, default='', null=True, verbose_name='summary description')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='picture product')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='product price')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is active')),
                ('register_date', models.DateField(auto_now_add=True, null=True, verbose_name='create date')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='publish date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='update date')),
                ('slug', models.SlugField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='image brand'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='group photo'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='feature value')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='feature')),
                ('filter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.featurevalue', verbose_name='feature value fiter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product feature',
                'verbose_name_plural': 'product features',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_of_brands', to='products.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='products.ProductFeature', to='products.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='products.productgroup', verbose_name='product group'),
        ),
    ]
